/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.

In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth 2.0</a>.

The base URI for all Web API requests is `https://api.spotify.com/v1`.

Need help? See our <a href="https://developer.spotify.com/documentation/web-api/guides/">Web API guides</a> for more information, or visit the <a href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify for Developers community forum</a> to ask questions and connect with other developers.

 * OpenAPI spec version: 2023.8.30
 */
import axios from 'axios'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import useSwr from 'swr'
import type {
  Key,
  SWRConfiguration
} from 'swr'
import type {
  AddToQueueParams,
  CursorPagedPlayHistoryResponse,
  ForbiddenResponse,
  GetInformationAboutTheUsersCurrentPlaybackParams,
  GetRecentlyPlayedParams,
  GetTheUsersCurrentlyPlayingTrackParams,
  ManyDevicesResponse,
  OneCurrentlyPlayingResponse,
  OneCurrentlyPlayingTrackResponse,
  PauseAUsersPlaybackParams,
  QueueResponse,
  SeekToPositionInCurrentlyPlayingTrackParams,
  SetRepeatModeOnUsersPlaybackParams,
  SetVolumeForUsersPlaybackParams,
  SkipUsersPlaybackToNextTrackParams,
  SkipUsersPlaybackToPreviousTrackParams,
  StartAUsersPlaybackBody,
  StartAUsersPlaybackParams,
  ToggleShuffleForUsersPlaybackParams,
  TooManyRequestsResponse,
  TransferAUsersPlaybackBody,
  UnauthorizedResponse
} from '../../model'


  
  /**
 * Get information about the user’s current playback state, including track or episode, progress, and active device.

 * @summary Get Playback State

 */
export const getInformationAboutTheUsersCurrentPlayback = (
    params?: GetInformationAboutTheUsersCurrentPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OneCurrentlyPlayingResponse | void>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/player`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetInformationAboutTheUsersCurrentPlaybackKey = (params?: GetInformationAboutTheUsersCurrentPlaybackParams,) => [`https://api.spotify.com/v1/me/player`, ...(params ? [params]: [])] as const;

    
export type GetInformationAboutTheUsersCurrentPlaybackQueryResult = NonNullable<Awaited<ReturnType<typeof getInformationAboutTheUsersCurrentPlayback>>>
export type GetInformationAboutTheUsersCurrentPlaybackQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Playback State

 */
export const useGetInformationAboutTheUsersCurrentPlayback = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
 params?: GetInformationAboutTheUsersCurrentPlaybackParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getInformationAboutTheUsersCurrentPlayback>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }

  ) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetInformationAboutTheUsersCurrentPlaybackKey(params) : null);
  const swrFn = () => getInformationAboutTheUsersCurrentPlayback(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Transfer playback to a new device and determine if it should start playing.

 * @summary Transfer Playback

 */
export const transferAUsersPlayback = (
    transferAUsersPlaybackBody: TransferAUsersPlaybackBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player`,
      transferAUsersPlaybackBody,options
    );
  }


/**
 * Get information about a user’s available devices.

 * @summary Get Available Devices

 */
export const getAUsersAvailableDevices = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ManyDevicesResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/player/devices`,options
    );
  }


export const getGetAUsersAvailableDevicesKey = () => [`https://api.spotify.com/v1/me/player/devices`] as const;

    
export type GetAUsersAvailableDevicesQueryResult = NonNullable<Awaited<ReturnType<typeof getAUsersAvailableDevices>>>
export type GetAUsersAvailableDevicesQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Available Devices

 */
export const useGetAUsersAvailableDevices = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAUsersAvailableDevices>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }

  ) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAUsersAvailableDevicesKey() : null);
  const swrFn = () => getAUsersAvailableDevices(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get the object currently being played on the user's Spotify account.

 * @summary Get Currently Playing Track

 */
export const getTheUsersCurrentlyPlayingTrack = (
    params?: GetTheUsersCurrentlyPlayingTrackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OneCurrentlyPlayingTrackResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/player/currently-playing`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetTheUsersCurrentlyPlayingTrackKey = (params?: GetTheUsersCurrentlyPlayingTrackParams,) => [`https://api.spotify.com/v1/me/player/currently-playing`, ...(params ? [params]: [])] as const;

    
export type GetTheUsersCurrentlyPlayingTrackQueryResult = NonNullable<Awaited<ReturnType<typeof getTheUsersCurrentlyPlayingTrack>>>
export type GetTheUsersCurrentlyPlayingTrackQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Currently Playing Track

 */
export const useGetTheUsersCurrentlyPlayingTrack = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
 params?: GetTheUsersCurrentlyPlayingTrackParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTheUsersCurrentlyPlayingTrack>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }

  ) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTheUsersCurrentlyPlayingTrackKey(params) : null);
  const swrFn = () => getTheUsersCurrentlyPlayingTrack(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Start a new context or resume current playback on the user's active device.

 * @summary Start/Resume Playback

 */
export const startAUsersPlayback = (
    startAUsersPlaybackBody: StartAUsersPlaybackBody,
    params?: StartAUsersPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/play`,
      startAUsersPlaybackBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Pause playback on the user's account.

 * @summary Pause Playback

 */
export const pauseAUsersPlayback = (
    params?: PauseAUsersPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/pause`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Skips to next track in the user’s queue.

 * @summary Skip To Next

 */
export const skipUsersPlaybackToNextTrack = (
    params?: SkipUsersPlaybackToNextTrackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `https://api.spotify.com/v1/me/player/next`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Skips to previous track in the user’s queue.

 * @summary Skip To Previous

 */
export const skipUsersPlaybackToPreviousTrack = (
    params?: SkipUsersPlaybackToPreviousTrackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `https://api.spotify.com/v1/me/player/previous`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Seeks to the given position in the user’s currently playing track.

 * @summary Seek To Position

 */
export const seekToPositionInCurrentlyPlayingTrack = (
    params: SeekToPositionInCurrentlyPlayingTrackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/seek`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Set the repeat mode for the user's playback. Options are repeat-track,
repeat-context, and off.

 * @summary Set Repeat Mode

 */
export const setRepeatModeOnUsersPlayback = (
    params: SetRepeatModeOnUsersPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/repeat`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Set the volume for the user’s current playback device.

 * @summary Set Playback Volume

 */
export const setVolumeForUsersPlayback = (
    params: SetVolumeForUsersPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/volume`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Toggle shuffle on or off for user’s playback.

 * @summary Toggle Playback Shuffle

 */
export const toggleShuffleForUsersPlayback = (
    params: ToggleShuffleForUsersPlaybackParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.put(
      `https://api.spotify.com/v1/me/player/shuffle`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


/**
 * Get tracks from the current user's recently played tracks.
_**Note**: Currently doesn't support podcast episodes._

 * @summary Get Recently Played Tracks

 */
export const getRecentlyPlayed = (
    params?: GetRecentlyPlayedParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CursorPagedPlayHistoryResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/player/recently-played`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetRecentlyPlayedKey = (params?: GetRecentlyPlayedParams,) => [`https://api.spotify.com/v1/me/player/recently-played`, ...(params ? [params]: [])] as const;

    
export type GetRecentlyPlayedQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentlyPlayed>>>
export type GetRecentlyPlayedQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get Recently Played Tracks

 */
export const useGetRecentlyPlayed = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
 params?: GetRecentlyPlayedParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getRecentlyPlayed>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }

  ) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetRecentlyPlayedKey(params) : null);
  const swrFn = () => getRecentlyPlayed(params, axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Get the list of objects that make up the user's queue.

 * @summary Get the User's Queue

 */
export const getQueue = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<QueueResponse>> => {
    return axios.get(
      `https://api.spotify.com/v1/me/player/queue`,options
    );
  }


export const getGetQueueKey = () => [`https://api.spotify.com/v1/me/player/queue`] as const;

    
export type GetQueueQueryResult = NonNullable<Awaited<ReturnType<typeof getQueue>>>
export type GetQueueQueryError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>

/**
 * @summary Get the User's Queue

 */
export const useGetQueue = <TError = AxiosError<UnauthorizedResponse | ForbiddenResponse | TooManyRequestsResponse>>(
  options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getQueue>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }

  ) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
    const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetQueueKey() : null);
  const swrFn = () => getQueue(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}

/**
 * Add an item to the end of the user's current playback queue.

 * @summary Add Item to Playback Queue

 */
export const addToQueue = (
    params: AddToQueueParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.post(
      `https://api.spotify.com/v1/me/player/queue`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


